import { IOpenDataService } from "@/src/application/services/open-data-service.interface";
import { RowOpenData } from "@/src/entities/open-data-training";

export class MockOpenDataService implements IOpenDataService {
  getTrainings(): Promise<RowOpenData[]> {
    return new Promise((resolve) => {
      const data = [
        {
          session: "2023",
          contrat_etab: "Public",
          cod_uai: "0010016M",
          g_ea_lib_vx: "Lyc\u00e9e Joseph-Marie Carriat",
          dep: "01",
          dep_lib: "Ain",
          region_etab_aff: "Auvergne-Rh\u00f4ne-Alpes",
          acad_mies: "Lyon",
          ville_etab: "Bourg-en-Bresse",
          lib_for_voe_ins: "BTS - Services - Comptabilit\u00e9 et gestion",
          select_form: "formation s\u00e9lective",
          fili: "BTS",
          lib_comp_voe_ins:
            "Lyc\u00e9e Joseph-Marie Carriat - BTS - Services - Comptabilit\u00e9 et gestion",
          form_lib_voe_acc: "BTS - Services",
          fil_lib_voe_acc: "Comptabilit\u00e9 et gestion",
          detail_forma: null,
          g_olocalisation_des_formations: { lon: 5.22398, lat: 46.197 },
          capa_fin: 40,
          voe_tot: 508,
          voe_tot_f: 243,
          nb_voe_pp: 477,
          nb_voe_pp_internat: null,
          nb_voe_pp_bg: 51,
          nb_voe_pp_bg_brs: 15,
          nb_voe_pp_bt: 144,
          nb_voe_pp_bt_brs: 55,
          nb_voe_pp_bp: 63,
          nb_voe_pp_bp_brs: 33,
          nb_voe_pp_at: 219,
          nb_voe_pc: 31,
          nb_voe_pc_bg: 2,
          nb_voe_pc_bt: 0,
          nb_voe_pc_bp: 15,
          nb_voe_pc_at: 14,
          nb_cla_pp: 258,
          nb_cla_pc: 5,
          nb_cla_pp_internat: null,
          nb_cla_pp_pasinternat: null,
          nb_cla_pp_bg: 46,
          nb_cla_pp_bg_brs: 13,
          nb_cla_pp_bt: 121,
          nb_cla_pp_bt_brs: 43,
          nb_cla_pp_bp: 39,
          nb_cla_pp_bp_brs: 22,
          nb_cla_pp_at: 52,
          prop_tot: 158,
          acc_tot: 33,
          acc_tot_f: 17,
          acc_pp: 32,
          acc_pc: 0,
          acc_debutpp: 7.0,
          acc_datebac: 25.0,
          acc_finpp: 25.0,
          acc_internat: null,
          acc_brs: 8,
          acc_neobac: 22,
          acc_bg: 3,
          acc_bt: 13,
          acc_bp: 6,
          acc_at: 11,
          acc_mention_nonrenseignee: 0,
          acc_sansmention: 13,
          acc_ab: 7,
          acc_b: 2,
          acc_tb: 0,
          acc_tbf: 0.0,
          acc_bg_mention: 1,
          acc_bt_mention: 5,
          acc_bp_mention: 3,
          acc_term: 9,
          acc_term_f: 2,
          acc_aca_orig: 18,
          acc_aca_orig_idf: 18,
          pct_acc_debutpp: 21.0,
          pct_acc_datebac: 76.0,
          pct_acc_finpp: 76.0,
          pct_f: 52.0,
          pct_aca_orig: 82.0,
          pct_aca_orig_idf: 82.0,
          pct_etab_orig: 41.0,
          pct_bours: 36.0,
          pct_neobac: 67.0,
          pct_mention_nonrenseignee: 0.0,
          pct_sansmention: 59.0,
          pct_ab: 32.0,
          pct_b: 9.0,
          pct_tb: 0.0,
          pct_tbf: 0.0,
          pct_bg: 14.0,
          pct_bg_mention: 5.0,
          pct_bt: 59.0,
          pct_bt_mention: 23.0,
          pct_bp: 27.0,
          pct_bp_mention: 14.0,
          prop_tot_bg: 24.0,
          prop_tot_bg_brs: 5.0,
          prop_tot_bt: 63.0,
          prop_tot_bt_brs: 23.0,
          prop_tot_bp: 39.0,
          prop_tot_bp_brs: 22.0,
          prop_tot_at: 32.0,
          lib_grp1: "Autres candidats",
          ran_grp1: 64.0,
          lib_grp2: "Bacheliers professionnels toutes series",
          ran_grp2: 41.0,
          lib_grp3: "Bacheliers technologiques toutes series",
          ran_grp3: "143",
          list_com: "Liste d'appel propre \u00e0 cette formation",
          tri: "2_Lyc\u00e9es",
          cod_aff_form: "2009",
          detail_forma2: null,
          lien_form_psup:
            // "https://dossier.parcoursup.fr/Candidats/public/fiches/afficherFicheFormation?g_ta_cod=2009",
            "https://dossier.parcoursup.fr/Candidats/public/fiches/afficherFicheFormation?g_ta_cod=4",

          taux_acces_ens: 61.0,
          part_acces_gen: 26.0,
          part_acces_tec: 54.0,
          part_acces_pro: 20.0,
          etablissement_id_paysage: null,
          composante_id_paysage: null,
        },
      ];

      resolve(data);
    });
  }
}
